void resetstack(void);
void underflow(void);
void i_pop(void);
void clriseg(void);
void pushiseg(void);
Codep inodes2code(Instnodep inlist);
Codep popiseg(void);
void rminstnode(Instnodep t,Instnodep prei,int adjust);
void instnodepatch(Instnodep t,Instnodep i1,Instnodep i2);
void optiseg(Instnodep t);
Instnodep futureinstnode(void);
void addinode(Instnodep in);
Instnodep code(Instcode ic);
Instcode numinst(int n);
Instcode strinst(Symstr s);
Instcode dblinst(double d);
Instcode syminst(Symbolp s);
Instcode phrinst(Phrasep p);
Instcode instnodeinst(Instnodep n);
Instcode realfuncinst(BYTEFUNC f);
Instcode bltininst(BLTINCODE f);
Instnodep previnstnode(register Instnodep ilow,register Instnodep in);
Instcode* ptincode(register Instnodep in,register int n);
void i_dblpush(void);
void i_stringpush(void);
void i_phrasepush(void);
void makeroom(long n,char **aptr,long *asize);
void reinitmsg2(void);
void ptomsg2(register Symstr s);
void reinitmsg3(void);
void ptomsg3(register Symstr s);
Symstr phrstr(Phrasep p, int nl);
Symstr dtostr(Datum d);
Datum dtoindex(Datum d);
void expectarr(Datum d,Datum subs,char *s);
void i_arrend(void);
void i_arraypush(void);
void i_incond(void);
void startclass(Symbolp sp);
void endclass(Symbolp sp);
void startdef(register Symbolp sp);
void enddef(register Symbolp sp);
void callfuncd(Symbolp s);
#ifdef OLDSTUFF
void chkstk(void);
void prtstk(void);
#endif
void ret(Datum retd);
void redoarg0(Ktaskp t);
Datum * symdataptr(Symbolp s);
void i_divcode(void);
void i_par(void);
void i_amp(void);
Datum dlshift(Datum d1,Datum d2);
Datum drightshift(Datum d1,Datum d2);
void i_lshift(void);
void i_rightshift(void);
void i_negate(void);
void i_tilda(void);
void i_lt(void);
void i_gt(void);
void i_le(void);
void i_ge(void);
void i_ne(void);
void i_eq(void);
void i_regexeq(void);
int dcompare(Datum d1,Datum d2);
void i_and1(void);
void i_or1(void);
void i_not(void);
void prdatum(Datum d,STRFUNC outfunc,int quotes);
void i_noop(void);
void prstack(Datum *d);
