#pragma once

#include "stdio.h"
#include "stdlib.h"
#include "defines.h"

extern Symlongp Sweepquant;
extern Symlongp Dragquant;
extern Symlongp Bendrange, Bendoffset, Showtext, Showbar;
extern Symlongp Volstem, Volstemsize, Panraster, Colors;
extern Symlongp Colornotes, Inverse, Menujump, Menuscrollwidth, Menusize;
extern Symlongp Graphmode, Graphdriver, Menuymargin;
extern Symlongp Textscrollsize;
extern Symlongp Keyinverse, Cursereverse, Usewindfifos;
extern int Backcolor, Forecolor, Pickcolor, Lightcolor, Darkcolor;
extern Phrasepp Pickphr, Gridphr;
extern Symstrp Fontname, Icon, Windowsys;
extern int Rawx, Rawy;
extern long Lastst, Lastsh;
extern int Lastxs, Lastys;
extern Kwind *Wind;
extern int Nwind;
extern Kwind *Wroot, *Wprintf;
extern Kwind *Topwind;
extern Htablep Windhash;

#ifdef __STDC__
typedef void (*NOTEFNCPTR)(struct Kwind*,Noteptr);
typedef void (*WINDFUNC)(struct Kwind*);
typedef void (*KWFUNC)(Kwind*,int,int,int,int);
#else
typedef void (*NOTEFNCPTR)();
typedef void (*WINDFUNC)();
typedef void (*KWFUNC)();
#endif
extern struct bltinfo builtins[];
extern BYTEFUNC Bytefuncs[];
extern char *Bytenames[];
extern BLTINFUNC Bltinfuncs[];

extern Midiport Midiinputs[MIDI_IN_DEVICES];
extern Midiport Midioutputs[MIDI_OUT_DEVICES];

extern Sched *Topsched;
extern long Earliest;
extern Htablep Keywords;
extern Htablep Macros;

extern int Nblocked;
extern int Nwaiting;
extern int Nsleeptill;

extern Ktaskp T;
extern Ktaskp Tboot;
extern Ktaskp Running;
extern int Currpriority;
extern Codep Ipop;
extern Fifo *Midi_in_f, *Midi_out_f;
extern Fifo *Consinf, *Consoutf, *Mousef;
extern int Consolefd, Midifd, Displayfd;
extern int Default_fifotype;
extern Kobjectp Topobj;
extern long Nextobjid;
extern Codep Idosweep;

extern int State;
extern actfunc Currfunc;
extern int Currchan;
extern Unchar* Currmessage;
extern int Messleng;
extern int Messindex;
extern int Runnable;
extern struct midiaction Midi;


extern Noteptr Pend;		/* list of pending note-offs */
extern FILE *Trktmp;
extern char Tmpfname[16];	/* enough space for "#xxxxx.tmp" */
extern long Trksize;
extern FILE *Outf;
extern double Clickfactor;
extern int Laststat;	/* NOTEON, NOTEOFF, PRESSURE, etc. */

extern Kwind* Topwind;
extern Kwind* Freewind;
extern Htablep Windhash;

extern int Menuysize;

extern int Mf_nomerge;
extern long Mf_currtime;
extern int Mf_skipinit;
extern FILE *Mf;
extern long Mf_toberead;
extern int Tracknum;
extern Phrasep Noteq;
extern Phrasep Currph;
extern int Numq;
extern double Clickfactor;
extern Htablep Mfarr;
extern int Mformat;

extern Kwind* Topwind;
extern Kwind* Freewind;
extern Htablep Windhash;

extern int Menuysize;

extern Instcode Stopcode;

extern Datum _Dnumtmp_;

extern Unchar B___;

void keyerrfile(char *fmt,...);

int keymain(int argc, char** argv);
void initExterns();

extern int Anyrun;
extern int Cprio;
extern Datum lsdatum;
extern char * lsdir;
extern int lsdirleng;
extern int Codesize[9];
extern int Indef, Inclass;
extern int Globaldecl;
extern int Inparams;
extern int Inselect;
extern int Paramnum;
extern int Niseg;
extern char *Pyytext;
extern char *Progname;
extern char *Yytext;
extern char *Yytextend;
extern char *Buffer;
extern char *Msg1, *Msg2, *Msg3;
extern long Msg1size, Msg2size, Msg3size;
extern long Msgtsize;
extern char *Msgt;
extern char* Wmsg;
extern long Wmsgsize;
extern char* Ungot;
extern int Loopnum;
extern char* stdinonly[];
extern long Ungotsize;
extern unsigned int Buffsize;
extern int yydebug;
extern FILE *Fin, *Fout;
extern Datum Zeroval, Noval, Nullval;
extern Datum Str_x0, Str_y0, Str_x1, Str_y1, Str_x, Str_y, Str_button;
extern Datum Str_type, Str_mouse, Str_down, Str_up, Str_drag, Str_move;
extern Datum Str_lowest, Str_highest, Str_earliest, Str_latest, Str_modifier;
extern Datum Str_default, Str_w, Str_r, Str_init;
extern Datum Str_get, Str_set, Str_newline;
extern Datum Str_red, Str_green, Str_blue, Str_grey, Str_surface;
extern Datum Str_finger, Str_hand, Str_xvel, Str_yvel;
extern Datum Str_width, Str_height;
extern Datum Str_proximity, Str_orientation, Str_eccentricity;
#ifdef MDEP_OSC_SUPPORT
extern Datum Str_elements, Str_seconds, Str_fraction;
#endif
extern int Doconsole, Gotanint;
extern Instnodep *Future, *Iseg, *Lastin;
extern Instnodep Beingread;
extern Symstr _Icstr;
extern DBLTYPE _Icdbl;
extern Symbolp _Icsym;
extern long _Icval;
extern Phrasep _Icphr;
extern Codep _Icin;
extern Phrasep Tobechecked;
extern Htablep Htobechecked;
extern struct bi_bitmap_t* Bitmaplist;

extern char* Nullstr;
extern int Defvol, Defoct, Defchan, Defport;
extern DURATIONTYPE Defdur;
extern char *Defatt;
extern long Deftime;
extern long Def2time;
extern UINT16 Defflags;

extern Noteptr Freent;
extern Phrasep Topph;
extern Phrasep Freeph;

extern int Numnotes;
extern int Numalloc;

extern Symlongp Mousebutt;
extern Symlongp Sweepquant, Menuymargin;
extern Symlongp Rtmouse;
extern Symlongp Dragquant;
extern Symlongp Keyinverse, Panraster;
extern Symlongp Bendrange, Bendoffset, Showtext, Showbar;
extern Symlongp Volstem, Volstemsize, Colors, Colornotes;
extern Symlongp Inverse, Menusize, Menujump, Menuscrollwidth, Menusize;
extern Symlongp Textscrollsize;

extern int Pmode;
extern int Backcolor;
extern int Forecolor;
extern int Pickcolor;
extern int Lightcolor;
extern int Darkcolor;

extern Kwind *Wroot;
extern Kwind *Wprintf;

extern long Lastst;
extern int Lastxs;
extern long Lastsh;
extern int Lastys;

extern long Lastst;
extern int Lastxs;
extern long Lastsh;
extern int Lastys;

extern Instnodep* Iseg;
extern Instnodep* Lastin;
extern Instnodep* Future;

extern int Maxiseg;
extern int Niseg;
extern Instcode Stopcode;

extern Htablep Fifotable;
extern Fifo *Topfifo;
extern Fifo *Freefifo;
extern int Nblocked;
extern long Fifonum;
extern int Default_fifotype;

extern Fifo *Midi_in_f;
extern Fifo *Midi_out_f;
extern Fifo *Consinf;
extern Fifo *Consoutf;
extern Fifo *Mousef;

extern Htablep Newarr;
extern int Chkstuff;
extern int Keycnt;
extern int Argc;
extern char **Argv;
extern Codep Fkeyfunc[NFKEYS];
extern int Errors;
extern int Errfileit;
extern int Pmode;
extern int Lineno;
extern Instnodep Loopstack[FSTACKSIZE];
extern int Loopnum;
extern Codep Fkeyfunc[NFKEYS];


extern char Tty[];
extern char* Infile;
extern char Autopop;

extern FILE *Fstack[FSTACKSIZE];	/* Nested FILEs being read */
extern char *Fnstack[FSTACKSIZE];	/* The names of those files */
extern int Lnstack[FSTACKSIZE];		/* Current line # in those files */
extern int Popstack[FSTACKSIZE];	/* Whether to auto-pop on EOF */
extern FILE **Fstackp;
extern char **Fnstackp;
extern int *Lnstackp;
extern int *Popstackp;
extern long Ungoti;
extern int Maxpathleng;
extern Htablep Keylibtable;

/*
 * first index is 0 (for defaults) or 0-based input port number+1,
 * second index is 0-based channel.  The value is the 1-based output port #.
 */
extern int Portmap[PORTMAP_SIZE][16];

extern Context *Topct, *Currct;
extern Htablep Topht;
extern Htablep Tasktable;
extern char *Scachars[];
extern Datum *Errorfuncd, *Rebootfuncd, *Printfuncd;
extern Datum *Intrfuncd;
extern long Tempo;
extern float Milliperclick;
extern int Setintr;
extern int Macrosused;
extern char *Infile;
extern int Erasechar, Killchar, Intrchar, Eofchar;
extern int Nonotealloc;
extern long Seqnum;
extern Datum *Colorfuncd, *Redrawfuncd, *Resizefuncd, *Exitfuncd;
extern Htablepp Track;
extern Htablepp Chancolormap;
extern int Midiok;
extern long Chkcount;

/* Global keykit variables */
extern Symlongp Clicks, Merge, Debug, Now, Sync, Lag, Graphics, Mergefilter;
extern Symlongp Mergeport1, Mergeport2;
extern Symlongp Debugwait, Debugmidi, Debugrun, Optimize, Debugfifo, Debugmouse;
extern Symlongp Clocksperclick, Clicksperclock, Inputistty, Recsysex;
extern Symlongp Filter, Record, Recsched, Debugdraw, Recfilter, Recinput;
extern Symlongp Loadverbose, Throttle2, Warnnegative, Midifilenoteoff;
extern Symlongp Drawcount, Mousedisable, Forceinputport, Mfsysextype;
extern Symlongp Lowcorelim, Arraysort, Tempotrack, Debugoff, Fakewrap;
extern Symlongp Defrelease, Onoffmerge, Grablimit, Mfformat, Defoutport;
extern Symlongp Taskaddr, Debuginst, Prepoll, Debugmalloc, Linetrace;
extern Symlongp Debugkill, Debugkill1, Consecho, Abortonint, Abortonerr;
extern Symlongp Checkcount, Isofuncwarn, Resizefix, Consupdown, Slashcheck;
extern Symlongp Novalval, Eofval, Intrval, Nowoffset, Directcount, SubstrCount;
extern Symlongp Printsplit, Throttle, Defpriority, Showsync, Echoport;
extern Symlongp Offsetpitch, Offsetfilter, Monitor_fnum, Consecho_fnum;
extern Symlongp Offsetportfilter;
extern Symlongp Consinfnum, Consoutfnum, Midi_in_fnum, Midi_out_fnum;
extern Symlongp Redrawignoretime, Resizeignoretime, Mousefnum, Warningsleep;
extern Symlongp Millires, Milliwarn, Mousefifolimit, Minbardx, Midithrottle;
extern Symlongp Numinst1, Numinst2, Kobjectoffset, Mousemoveevents;
extern Symlongp Debuggesture;
extern Symlongp Chancolors;
extern Phrasepp Currphr, Recphr;
extern Symstrp Keypath, Musicpath, Keyroot, Initconfig;
extern Symstrp Printsep, Printend, Pathsep, Dirseparator, Devmidi, Machine;
extern int Dbg, Inerror, Usestdio, ReadytoEval;
extern void (*Fatalfunc)(char *);
extern void (*Diagfunc)(char *);
extern void checkdebug();

int yyparse(NOARG);

void startgraphics(void);
void my_plotmode(int m);
void showsane(Kwind *w);
void redrawpwind(Kwind *w);
void drawbars(Kwind *w,int sx,int sy,int ex,int ey);
void centertext(char *s,int x,int y);
void righttext(char *s,int x,int y);
void gridphresh(Phrasepp aph);
int windorigx(Kwind *w);
void drawph(Kwind *w,Phrasep p);
void setupchancolors(void);
void drawclipped(Kwind *w,Phrasep p,long sclicks,long eclicks,int spitch,int epitch,int sx,int sy,int ex,int ey);
void setnotecolor(Noteptr n, int color);
Noteptr closestnt(Kwind *w,Phrasep ph,int x,int y);
void drawnonnt(Kwind *w,Noteptr n,Krect *r);
char * nonnoteinfo(Kwind *w,Noteptr n,int *ay1,int *ay2);
char * textnoteinfo(Kwind *w,Noteptr n,int *ax1, int *ay1, int *ax2, int *ay2);
void nonnotesize(Noteptr n,int *apitch1,int *apitch2);
int ntbox(Kwind *w,Noteptr n,int *ax0,int *ay0,int *ax1,int *ay1,Krect *r);
int clipcode(Kwind *w,int x,int y,Krect *r);
int fullclipit(Kwind *w,int *x1,int *y1,int *x2,int *y2,Krect *r);
int rectclipit(Kwind *w,int *x1,int *y1,int *x2,int *y2,Krect *r);
void gridline(Kwind *w,long clks1,int pitch1,long clks2,int pitch2);
void gridtext(Kwind *w,long clks1,int pitch1,char *str);
int dispclip(Kwind *w,int *ax,int *ay,Krect *kr);
long longquant(long v,long q);
int pitchyraw(Kwind *w,int pitch);
int pitchtoy(Kwind *w,int pitch);
void xytogrid(Kwind *w,long x,long y,long *aclick,long *apitch,long quant);
void pharea(Phrasep ph,long *astart,long *aend,long *alow,long *ahigh);
void gridpan(Kwind *w,long cshift,int pshift);
void wredraw1(Kwind *w);
void woutline(Kwind *w);
void wshadow(Kwind *w,int menubutton,int pressed);
void werase(Kwind *w);
Kwind * validwind(int n,char *s);
Kwind * windptr(int n);
void windlist(void);
Kwind * windfinddeep(Kwind *w,int x,int y);
int windcontains(Kwind *w,long x0,long y0);
int windlevel(Kwind *w);
int windoverlaps(Kwind *w,long x0,long y0,long x1,long y1);
void reinitwinds(void);
void setwrootsize(void);
Datum winddatum(Kwind *w);
Kwind * newkwind(void);
void k_initphrase(Kwind *w);
void k_inittext(Kwind *w);
void k_reinittext(Kwind *w);
void kwindtext(Symstr str,int kx0,int ky0,int kx1,int ky1,int just);
void textfill(char *s,int x0,int y0,int x1,int y1,int just);
void kwindline(Kwind *w,int x0,int y0,int x1,int y1);
void kwindrect(Kwind *w,int x0,int y0,int x1,int y1);
void kwindfill(Kwind *w,int x0,int y0,int x1,int y1);
void kwindrect2(Kwind *w,int x0,int y0,int x1,int y1,int dofill);
void kwindellipse(Kwind *w,int x0,int y0,int x1,int y1);
void kwindfillellipse(Kwind *w,int x0,int y0,int x1,int y1);
void kwindellipse2(Kwind *w,int x0,int y0,int x1,int y1,int dofill);
void kwindfillpolygon(Kwind *w,int *xarr,int *yarr,int arrsize);
void rectnorml(long *ax0,long *ay0,long *ax1,long *ay1);
void rectnormi(int *ax0,int *ay0,int *ax1,int *ay1);
void scalexy(long *ax,long *ay,long fromx0,long fromy0,long fromx1,long fromy1,long tox0,long toy0,long tox1,long toy1);
void scalephr2raw(Kwind *w,long *ax,long *ay);
void scalegrid2wind(Kwind *w,long *ax,long *ay);
void scalewind2grid(Kwind *w,long *ax,long *ay);
void k_setsize(Kwind *w,int x0,int y0,int x1,int y1);
Kitem * newkitem(char *name);
Kitem * k_findmenuitem(Symstr name,Kwind *w,int create);
void windhashdelete(Kwind *w);
void wfree(Kwind *w);
void wunlink(Kwind *w,Kwind **tw);
void waddtolist(Kwind *w, Kwind **wlist);
void k_initmenu(Kwind *w);
Kitem * k_menuitem(Kwind *w,Symstr item);
Krect makerect(long x0, long y0, long x1, long y1);

void keystart(void);
void keyfile(char *fname,int flag);
void keydefine(char *s);
void keystr(char *s);
void defnonly(char *s);
void looponly(char *s);
void loopstart(void);
void looppatch(Instnodep patchin);
void loopend(Instnodep icontinue,Instnodep ibreak);
void yyerror(char *s);
char * ipfuncname(Codep cp);
char * infuncname(Instnodep in);
void pstacktrace(Datum *dp);
void stackbuffclear(void);
void stackbuff(char *s);
long stackbuffleng(void);
void stackbufftrunc(long lng);
char * stackbuffstr(void);
char * stacktrace(Datum *dp,int full,int newlines,Ktaskp t);
void keyerrfile(char *fmt,...);
void execerror(char *fmt,...);
void resetstuff(void);
void forcereboot(void);
void warning(char *fmt,...);
void popupwarning(char *fmt,...);
void finalexit(int r);
void realexit(int r);
void fatalerror(char *s);
void myre_fail(char *s,int c);
void tsync(void);
void tprint(char *fmt,...);
void eprint(char *fmt,...);
void kdoprnt(int addnewline, FILE *f, char *fmt, va_list args);
void intcatch(void);
void setintcatch(void);
void yyunget(int ch);
void stuffch(int ch);
void stuffword(char *q);
int yyinput(void);
void pushfin(FILE *f,char *fn,int autopop);
void popfin(void);
void yyreset(void);
void flushfin(void);
int yyrawin(void);
Codep instructs(char *s);
void corecheck(void);
int checkfunckey(int c);
int follow(int expect,int ifyes,int ifno);
int follo2(int expect1,int ifyes1,int expect2,int ifyes2,int ifno);
int follo3(int expect1,int ifyes1,int expect2,int expect3,int ifyes2,int ifyes3,int ifno);
int eatpound(void);
void plibrary(char *dir,char *s);
void load1keylib(char *dir, char *keylibk);
void loadkeylibk(void);
void addplibrary(char *dir,char *fname,char *funcname);
void pinclude(char *s);
void macrodefine(char *s,int checkkeyword);
int scanparam(char **ap);
void macroeval(char *name);
char * scantill(char *lookfor,char *buff,char *pend);
void readkeylibs(void);
Symstr filedefining(char *fnc);
int loadsymfile(Symbolp s,int pushit);
Phrasep filetoph(FILE *f,char *fname);
char * kpathsearch(char *fname);
char * mpathsearch(char *fname);
char * pathsearch(char *fname,long *apathsize,char ***apathparts,Symstrp alastkeypath,char **apathfname,Symstrp pathvar,PATHFUNC pfunc);
char ** makeparts(Symstr path);

char * funcnameof(BYTEFUNC i);
Ktaskp taskptr(long tid);
void restartexec(void);
void makesuredefined(Datum **dpp,char *nm);
void checkports(void);
void handlewaitfor(int wn);
void exectasks(int nosetjmp);
void loadsym(Symbolp s,int pushit);
void i_vareval(void);
void i_objvareval(void);
void i_funcnamed(void);
void i_lvareval(void);
void i_gvareval(void);
void i_varpush(void);
void i_objvarpush(void);
void i_callfunc(void);
void i_objcallfuncpush(void);
void i_objcallfunc(void);
void i_array(void);
void filelinetrace(void);
void i_linenum(void);
void i_filename(void);
int printmeth(Hnodep h);
void i_pushinfo(void);
void i_popinfo(void);
void i_typeof(void);
void i_xy2(void);
void i_xy4(void);
void i_nargs(void);
void i_classinit(void);
void i_forin1(void);
void i_forin2(void);
void i_popnreturn(void);
void i_stop(void);
void i_select1(void);
void i_select2(void);
void i_select3(void);
void i_print(void);
void keyprintf(char *fmt,int arg0,int nargs, STRFUNC outfunc);
void checkmouse(void);
int handleconsole(void);
void doanint(void);
void i_goto(void);
void i_tfcondeval(void);
void i_tcondeval(void);
void i_constant(void);
void i_dotdotarg(void);
void i_varg(void);
void i_currobjeval(void);
void i_constobjeval(void);
void i_ecurrobjeval(void);
void i_erealobjeval(void);
void i_returnv(void);
void i_return(void);
void i_qmark(void);
void forinjumptoend(void);
void i_forinend(void);
void rmalltasksfifos(void);
void startreboot(void);
void nestinstruct(Codep cp);
void taskfunc0(Codep cp);
int pushdnodes(Dnode *dn,int move);
void taskfuncn(Codep cp,Dnode *dn);
void initstack(Ktaskp t);
Ktaskp newtask(Codep cp);
void setrunning(Ktaskp t);
void restarttask(Ktaskp t);
void taskunrun(Ktaskp t,int nstate);
int taskcollectchildren(Hnodep h);
void taskkill(Ktaskp t,int killchildren);
int taskunwait(Hnodep h);
void wakewaiters(Ktaskp t);
void taskbury(Ktaskp t);
void printrunning(char *s);
Ktaskp newtp(int state);
void linktask(Ktaskp p);
void freetp(Ktaskp t);
void deletetask(Ktaskp t);
void unlinktask(Ktaskp p);
void expandstack(Ktaskp p);
void expandstackatleast(Ktaskp p, int needed);
Codep infiniteloop(BYTEFUNC f);
void inittasks(void);
void eprfunc(BYTEFUNC i);

void initfifos(void);
Fifodata * newfd(Datum d);
void freefd(Fifodata *fd);
Fifo * fifoptr(long n);
int findport(Hnodep h);
Fifo * port2fifo(PORTHANDLE port);
void closefifo(Fifo *f);
void deletefifo(Fifo *f);
void freeff(Fifo *f);
void flushfifo(Fifo *f);
void flushlinebuff(Fifo* f);
void closeallfifos(void);
char * nameofchar(int c);
void putonconsinfifo(int c);
void putonconsoutfifo(char *s);
void putonconsechofifo(char *s);
void putonmousefifo(int mval,int x,int y,int pressed,int mod);
void putonmidiinfifo(Noteptr n);
void putntonfifo(Noteptr n,Fifo* f);
char * findopt(char *nm,char **args);
int isspecialfifo(Fifo *f);
Fifo * specialfifo(void);
Fifo * getafifo(void);
int fifoctl2type(char *mode, int def);
int mode2flags(char *mode);
int newfifo(char *fname,char *mode,char *porttype,Fifo **pf1,Fifo **pf2);
int fifosize(Fifo *f);
void getfromfifo(Fifo *f);
Datum removedatafromfifo(Fifo *f);
void blockfifo(Fifo *f,int noreturn);
void unblocktask(Ktaskp t);
void getfifo(Fifo *f);
void fputit(char *s);
void putfifo(Fifo *f,Datum d);

void i_popignore(void);
void i_defined(void);
void i_objdefined(void);
void i_currobjdefined(void);
void i_realobjdefined(void);
void i_task(void);
void undefsym(Symbolp s);
void i_undefine(void);
Phrasep phresh(Phrasep p);
Datum dphresh(Datum d);
long doop(long oldv,long v,int type);
Datum datumdoop(Datum od,Datum nd,int op);
Datum dmodulo(Datum d1,Datum d2);
void i_dot(void);
void i_modulo(void);
Symstr addstr(Symstr s1,Symstr s2);
Datum dadd(Datum d1,Datum d2);
void i_addcode(void);
Phrasep phrop(Phrasep p1,int op,Phrasep p2);
int phrcmp(Phrasep p1,Phrasep p2);
Datum dsub(Datum d1,Datum d2);
void i_subcode(void);
Datum dmul(Datum d1,Datum d2);
void i_mulcode(void);
Datum dxor(Datum d1,Datum d2);
void i_xorcode(void);
Datum ddiv(Datum d1,Datum d2);
Datum dpar(Datum d1,Datum d2);
Datum damp(Datum d1,Datum d2);
void setval(Noteptr n,int field,Datum nv);
Datum ntassign(Noteptr n,int dottype,Datum v,int op);
void phrvarinit(Symbolp s);
void i_dotassign(void);
void i_moddotassign(void);
void i_modassign(void);
void i_varassign(void);
void assign(int type, int dottype);
void fakeval(void);
void recodeassign(Instnodep varinode,Instnodep eqinode);
void i_deleteit(void);
void i_deletearritem(void);
int recodedelete(Instnodep exprinode,Instnodep lastinode);
void i_readonlyit(void);
void i_onchangeit(void);
void i_eval(void);

void resetstack(void);
void underflow(void);
void i_pop(void);
void clriseg(void);
void pushiseg(void);
Codep inodes2code(Instnodep inlist);
Codep popiseg(void);
void rminstnode(Instnodep t,Instnodep prei,int adjust);
void instnodepatch(Instnodep t,Instnodep i1,Instnodep i2);
void optiseg(Instnodep t);
Instnodep futureinstnode(void);
void addinode(Instnodep in);
Instnodep code(Instcode ic);
Instcode numinst(int n);
Instcode strinst(Symstr s);
Instcode dblinst(double d);
Instcode syminst(Symbolp s);
Instcode phrinst(Phrasep p);
Instcode instnodeinst(Instnodep n);
Instcode realfuncinst(BYTEFUNC f);
Instcode bltininst(BLTINCODE f);
Instnodep previnstnode(Instnodep ilow,Instnodep in);
Instcode* ptincode(Instnodep in,int n);
void i_dblpush(void);
void i_stringpush(void);
void i_phrasepush(void);
void makeroom(long n,char **aptr,long *asize);
void reinitmsg2(void);
void ptomsg2(Symstr s);
void reinitmsg3(void);
void ptomsg3(Symstr s);
Symstr phrstr(Phrasep p, int nl);
Symstr dtostr(Datum d);
Datum dtoindex(Datum d);
void expectarr(Datum d,Datum subs,char *s);
void i_arrend(void);
void i_arraypush(void);
void i_incond(void);
void startclass(Symbolp sp);
void endclass(Symbolp sp);
void startdef(Symbolp sp);
void enddef(Symbolp sp);
void callfuncd(Symbolp s);
void ret(Datum retd);
void redoarg0(Ktaskp t);
Datum * symdataptr(Symbolp s);
void i_divcode(void);
void i_par(void);
void i_amp(void);
Datum dlshift(Datum d1,Datum d2);
Datum drightshift(Datum d1,Datum d2);
void i_lshift(void);
void i_rightshift(void);
void i_negate(void);
void i_tilda(void);
void i_lt(void);
void i_gt(void);
void i_le(void);
void i_ge(void);
void i_ne(void);
void i_eq(void);
void i_regexeq(void);
int dcompare(Datum d1,Datum d2);
void i_and1(void);
void i_or1(void);
void i_not(void);
void prdatum(Datum d,STRFUNC outfunc,int quotes);
void i_noop(void);
void prstack(Datum *d);

void addtobechecked(Phrasep p);
void httobechecked(Htablep p);
void phrmerge(Phrasep p,Phrasep outp,long offset);
void phdump(void);
void ph1dump(Phrasep p);
void phcheck(void);
void htcheck(void);
char * strend(char *s);
unsigned int keyrand(void);
#ifdef OLDRAND
void keysrand(unsigned x);
#else
void keysrand (unsigned int seed1, unsigned int seed2, unsigned int seed3);
#endif
void phputc(int c);
void phputs(char *s);
void messprint(Noteptr nt);
void phprint(PFCHAR pfunc,Phrasep ph,int nl);
void nttostr(Noteptr n,char *buff);
int phsize(Phrasep p,int notes);
Noteptr picknt(Phrasep ph,int picknum);
int phrinphr(Datum d1,Datum d2);
char * atypestr(int type);
char * typestr(int type);
char * dotstr(int type);
Datum phdotvalue(Phrasep ph,int type);
int ntdotvalue(Noteptr n,int type,Datum *ad);
long getnumval(Datum d,int round);
double getdblval(Datum d);
int getnmtype(Datum d);
int findfile(char *name);
void getnclose(char *fname);
FILE * getnopen(char *name,char *mode);
void closefile(void);
void forinerr(void);
void inerr(void);
Instnodep newin(void);
void freeiseg(Instnodep in);
void freecode(Codep cp);
void freeinode(Instnodep in);
Lknode * newlk(Symstr nm);
void unlinklk(Lknode *lk);
void freelk(Lknode *lk);
Lknode * findtoplk(Symstr nm);
void unlocktid(Ktaskp t);
Ktaskp unlocklk(Lknode *lk);
void rmalllocks(void);
Kobjectp newobj(long id,int complain);
Kobjectp findobjnum(long n);
void unlinkobj(Kobjectp o);
void freeobj(Kobjectp o);
Dnode * newdn(void);
void freedn(Dnode *dn);
void freednodes(Dnode *dn);
Datum strdatum(char *s);
Datum dbldatum(double f);
Datum phrdatum(Phrasep p);
Datum codepdatum(Codep cp);
Datum framedatum(Datum *f);
Datum datumdatum(Datum *f);
Datum notedatum(Noteptr n);
Datum symdatum(Symbolp s);
Datum fifodatum(Fifo *f);
Datum taskdatum(Ktaskp t);
Datum arrdatum(Htablep arr);
Datum objdatum(Kobjectp obj);
Unchar * put_ipcode(Codep ip, Unchar *p);
Unchar * put_funccode(BYTEFUNC func, Unchar *p);
Unchar * put_bltincode(Unchar bltin, Unchar *p);
Unchar * put_strcode(Symstr str, Unchar *p);
Unchar * put_dblcode(DBLTYPE dbl, Unchar *p);
Unchar * put_numcode(long num, Unchar *p);
Unchar * put_symcode(Symbolp sym, Unchar *p);
Unchar * put_phrcode(Phrasep phr, Unchar *p);
Symstr scan_strcode(Unchar **pp);
Symbolp scan_symcode(Unchar **pp);
DBLTYPE scan_dblcode(Unchar **pp);
Phrasep scan_phrcode(Unchar **pp);
Codep scan_ipcode(Unchar **pp);
long nparamsof(Codep cp);
Symbolp symof(Codep cp);
long nlocalsof(Codep cp);
Codep firstinstof(Codep cp);
Unchar * varinum_put(long value,Unchar *p);
int varinum_size(long value);
long scan_numcode(Unchar **pp);
long scan_numcode1(Unchar **pp,int b);
#ifdef MDEP_OSC_SUPPORT
void osc_padit(char *msg,int msgsize,int *sofarp, int topad);
void osc_pack_str(char *msg,int msgsize,int *sofarp, char *s);
void osc_pack_int(char *msg,int msgsize,int *sofarp, int v);
void osc_pack_dbl(char *msg,int msgsize,int *sofarp, DBLTYPE v);
char * osc_scanstring(char **buff, int *buffsize);
int osc_scanint(char **buff, int *buffsize);
void osc_scantimetag(char **buff, int *buffsize, int *secs, int *fract);
int osc_scanblob(char **buff, int *buffsize, char *blobbuff, int blobbuffsize);
float osc_scanfloat(char **buff, int *buffsize);
Datum osc_array(char *buff, int buffsize, int used);
#endif

void newcontext(Symbolp s, int sz);
void popcontext(void);
Symbolp newsy(void);
void freesy(Symbolp sy);
Symbolp findsym(char *p,Htablep symbols);
Symbolp findobjsym(char *p,Kobjectp o,Kobjectp *foundobj);
Symbolp uniqvar(char* pre);
Symbolp lookup(char *p);
Symbolp localinstall(Symstr p,int t);
Symbolp globalinstall(Symstr p,int t);
Symbolp globalinstallnew(Symstr p,int t);
Symbolp syminstall(Symstr p,Htablep symbols,int t);
void clearsym(Symbolp s);
long neednum(char *s,Datum d);
Codep needfunc(char *s,Datum d);
Kobjectp needobj(char *s,Datum d);
Fifo * needfifo(char *s,Datum d);
Fifo * needvalidfifo(char *s,Datum d);
char * needstr(char *s,Datum d);
Htablep needarr(char *s,Datum d);
Phrasep needphr(char *s,Datum d);
Symstr datumstr(Datum d);
Datum newarrdatum(int used,int size);
Htablepp globarray(char *name);
Datum phrsplit(Phrasep p);
Datum strsplit(char *str,char *sep);
void setarraydata(Htablep arr,Datum i,Datum d);
void setarrayelem(Htablep arr,long n,char *p);
void fputdatum(FILE *f,Datum d);
void installnum(char *name,Symlongp *pvar,long defval);
void installstr(char *name,char *str);
Datum funcdp(Symbolp s, BLTINCODE f);
void initsyms(void);
void initsyms2(void);
void initstrs(void);
void pfprint(char *s);
void phtofile(FILE *f,Phrasep p);
void vartofile(Symbolp s, char *fname);
void filetovar(Symbolp s, char *fname);
Hnodep newhn(void);
void freehn(Hnodep hn);
Htablep newht(int size);
void clearht(Htablep ht);
void freeht(Htablep ht);
void htlists(void);
Symstr uniqstr(char *s);
int isundefd(Symbolp s);
Hnodep hashtable(Htablep ht,Datum key,int action);
Symbolp arraysym(Htablep arr,Datum subs,int action);
int arrsize(Htablep arr);
int dtcmp(Datum *d1,Datum *d2);
Datum * arrlist(Htablep arr,int *asize,int sortit);
void hashvisit(Htablep arr,HNODEFUNC f);

void bi_debug(int argc);
Datum limitsarr(Phrasep ph);
void bi_sizeof(int argc);
void bi_limitsof(int argc);
void bi_prstack(int argc);
void bi_phdump(int argc);
int tasklistcollect(Hnodep h);
void bi_taskinfo(int argc);
void bi_oldtypeof(int argc);
void bi_string(int argc);
void bi_integer(int argc);
void bi_float(int argc);
void bi_phrase(int argc);
void bi_sin(int argc);
void bi_cos(int argc);
void bi_tan(int argc);
void bi_asin(int argc);
void bi_acos(int argc);
void bi_atan(int argc);
void bi_sqrt(int argc);
void bi_exp(int argc);
void bi_log(int argc);
void bi_log10(int argc);
void bi_pow(int argc);
void bi_readphr(int argc);
void bi_pathsearch(int argc);
void bi_ascii(int argc);
void bi_reboot(int argc);
int funcundefine(Hnodep hn);
void bi_refunc(int argc);
void bi_rekeylib(int argc);
void bi_midifile(int argc);
void bi_split(int argc);
void bi_cut(int argc);
void bi_midibytes(int argc);
void bi_oldnargs(int argc);
void bi_error(int argc);
void bi_printf(int argc);
void bi_argv(int argc);
void nomidi(char *s);
void nographics(char *s);
void bi_realtime(int argc);
void bi_sleeptill(int argc);
void bi_wait(int argc);
void bi_lock(int argc);
void bi_unlock(int argc);
void bi_finishoff(int argc);
void bi_kill(int argc);
int chkprio(Hnodep h);
void bi_priority(int argc);
Dnode * grabargs(int fromargn,int toargn);
void bi_onexit(int argc);
void bi_onerror(int argc);
void bi_tempo(int argc);
void bi_substr(int argc);
void bi_sbbyes(int argc);
void bi_system(int argc);
void bi_chdir(int argc);
void lsdircallback(char *fname,int type);
void bi_lsdir(int argc);
void bi_filetime(int argc);
void bi_coreleft(int argc);
void bi_currtime(int argc);
void bi_milliclock(int argc);
void bi_rand(int argc);
void bi_exit(int argc);
void bi_garbcollect(int argc);
void bi_funkey(int argc);
void bi_symbolnamed(int argc);
void bi_windobject(int argc);
void bi_sync(int argc);
void bi_browsefiles(int argc);
void bi_setmouse(int argc);
void bi_mousewarp(int argc);
long arraynumval(Htablep arr,Datum arrindex,char *err);
int getxy01(Htablep arr,long *ax0,long *ay0,long *ax1,long *ay1,int normalize,char *err);
Datum xy01arr(long x0,long y0,long x1,long y1);
Datum xyarr(long x0,long y0);
int addifnew(Hnodep h);
void addnonxy(Htablep newarr,Htablep arr);
void bi_oldxy(int argc);
void bi_attribarray(int argc);
void bi_screen(int argc);
void wsettrack(Kwind *w,char *trk);
void bi_colorset(int argc);
void bi_colormix(int argc);
void bi_get(int argc);
void bi_put(int argc);
void bi_flush(int argc);
void bi_fifoctl(int argc);
void bi_mdep(int argc);
void chkinputport(int portno);
void chkoutputport(int portno);
void bi_midi(int argc);
void bi_bitmap(int argc);
void bi_help(int argc);
void bi_fifosize(int argc);
void validpitch(int n,char *s);
void bi_open(int argc);
void bi_close(int argc);
long newobjectid(void);
void bi_object(int argc);
void bi_objectlist(int argc);
void bi_objectinfo(int argc);
void bi_sprintf(int argc);
#ifdef MDEBUG
void bi_mmreset(int argc);
void bi_mmdump(int argc);
#endif
void bi_nullfunc(int argc);

void o_setinit(int argc);
void setelement(Kobjectp o,Symstr e,Datum d);
void setmethod(Kobjectp o,char *m,BLTINCODE i);
void setdata(Kobjectp o,char *m,Datum d);
Kobjectp defaultobject(long id,int complain);
void o_addchild(int argc);
#ifdef SAVEFORERRORCHECKING
void chksib(Kobjectp o1, char *s);
#endif
void o_removechild(int argc);
void o_children(int argc);
void o_addinherit(int argc);
void o_inherited(int argc);
Kwind* windid(Kobjectp o);
void o_size(int argc);
void o_contains(int argc);
void o_mousedo(int argc);
int needplotmode(char *meth,Datum d);
void o_lineboxfill(int argc,char *meth,KWFUNC f,int norm);
void o_fillpolygon(int argc);
void o_line(int argc);
void o_box(int argc);
void o_fill(int argc);
void o_ellipse(int argc);
void o_fillellipse(int argc);
void o_style(int argc);
void o_saveunder(int argc);
void o_restoreunder(int argc);
void o_textheight(int argc);
void o_textwidth(int argc);
void o_text(int argc,int just);
void o_printf(int argc);
void o_textcenter(int argc);
void o_textleft(int argc);
void o_textright(int argc);
void o_type(int argc);
void o_xmin(int argc);
void o_ymin(int argc);
void o_xmax(int argc);
void o_ymax(int argc);
void o_redraw(int argc);
void o_childunder(int argc);
void o_drawphrase(int argc);
void o_scaletogrid(int argc);
void o_scaletowind(int argc);
void o_closestnote(int argc);
void o_view(int argc);
void o_sweep(int argc);
void o_trackname(int argc);
void o_menuitem(int argc);
void o_menuitems(int argc);
Kobjectp windobject(long id,int complain,char *type);

void resetdef(void);
int saniport(long port);
Noteptr  newnt(void);
Midimessp savemess(Unchar* mess,int leng);
void ntfree(Noteptr n);
Noteptr  ntcopy(Noteptr n);
void freents(Noteptr n);
int bytescmp(Noteptr n1,Noteptr n2);
int utypeof(Noteptr nt);
int ntcmporder(Noteptr n1,Noteptr n2);
int ntcmpxact(Noteptr n1,Noteptr n2);
void phcopy(Phrasep out,Phrasep in);
void phreorder(Phrasep ph,long tmout);
void phcutusertype(Phrasep pin,Phrasep pout,int types,int invert);
void phcutcontroller(Phrasep pin,Phrasep pout,int cnum, int invert);
void phcutflags(Phrasep pin,Phrasep pout,long mask);
void phcutchannel(Phrasep pin,Phrasep pout,int chan);
void phcut(Phrasep pin,Phrasep pout,long tm1,long tm2,int p1,int p2);
void phcutincl(Phrasep pin,Phrasep pout,long tm1,long tm2);
void phcuttrunc(Phrasep pin,Phrasep pout,long tm1,long tm2);
Phrasep newph(int inituse);
void reinitph(Phrasep p);
void ntinsert(Noteptr n,Phrasep p);
void ntdelete(Phrasep ph,Noteptr nt);
int usertypeof(Noteptr nt);
int phtype(Phrasep p);
char * notetoke(INTFUNC infunc);
Phrasep yyphrase(INTFUNC infunc);
int strinput(void);
Phrasep strtophr(Symstr s);
int ntbytesleng(Noteptr n);
Noteptr  ntparse(char *s,Phrasep p);
char * attscan(char **s);
Noteptr  strtont(char *s);
Noteptr messtont(char *s);
Noteptr  strtotextmess(char *s);
Unchar* ptrtobyte(Noteptr n,int num);

int exists(char *fname);
void myfclose(FILE *f);
int hexchar(int c);
long numscan(char **as);
char * prlongto(long n,char *s);
char * printto(int n,char *s);
char * strsave(char *s);
int stdioname(char *fname);
void allocerror(void);
char * allocate(unsigned int s, char *tag);
char * dbgallocate(unsigned int s,char *tag);
void mmreset(void);
char * visstr(char *s);
void mmdump(void);
void myfree(char *s);
char * myfgets(char *buff, int bufsiz, FILE *f);

void midiparse(int inbyte);
void realmess(int inbyte);
void chanmsg(int inbyte);
void sysmess(int inbyte);
void biggermess(Unchar **amessage,int *aMessleng);

void arrtomf(Htablep arr,char *fname);

void mdep_hello(int argc,char **argv);
void mdep_bye(void);
int mdep_changedir(char *d);
char * mdep_currentdir(char *buff,int leng);
int mdep_lsdir(char *dir, char *exp, void (*callback)(char *,int));

extern int nbytenames;
static char* Grabbuff = NULL;
static long Grabbuffsize = 0;

extern int Midiok;
extern long Tempo;
extern long Milltempo;
extern long Start;

extern long Midinow;
extern long Midimilli;
extern long Nextclick;
extern int Chkmouse;
extern char Sustain[MIDI_OUT_DEVICES + 1][16];
extern char Portamento[MIDI_OUT_DEVICES + 1][16];

extern Datum lsdatum;
extern char * lsdir;
extern int lsdirleng;
extern Htablep Newarr;

long mdep_filetime(char *fn);
int mdep_fisatty(FILE *f);
long mdep_currtime(void);
long mdep_coreleft(void);
int mdep_full_or_relative_path(char *path);
int mdep_makepath(char *dirname, char *filename, char *result, int resultsize);

void mdep_popup(char *s);
int mdep_statconsole(void);
int mdep_getconsole(void);
void saveportevent(void);
Datum joyinit(int millipoll);
void joyrelease(void);
void mdep_prerc(void);
void mdep_initcolors(void);
char * mdep_keypath(void);
char * mdep_musicpath(void);
void mdep_postrc(void);
void mdep_abortexit(char *s);
int mdep_shellexec(char *s);
void mdep_setinterrupt(SIGFUNCTYPE i);
void mdep_ignoreinterrupt(void);
int mdep_waitfor(int tmout);
int mdep_startgraphics(int argc,char **argv);
char * mdep_browse(char *desc, char *types, int mustexist);
int mdep_screenresize(int x0, int y0, int x1, int y1);
int mdep_screensize(int *x0, int *y0, int *x1, int *y1);
int mdep_maxx(void);
int mdep_maxy(void);
void mdep_plotmode(int mode);
void mdep_endgraphics(void);
void mdep_destroywindow(void);
void mdep_line(int x0,int y0,int x1,int y1);
void mdep_box(int x0,int y0,int x1,int y1);
void mdep_boxfill(int x0,int y0,int x1,int y1);
void mdep_ellipse(int x0,int y0,int x1,int y1);
void mdep_fillellipse(int x0,int y0,int x1,int y1);
void mdep_fillpolygon(int *xarr,int *yarr,int arrsize);
Pbitmap mdep_allocbitmap(int xsize,int ysize);
Pbitmap mdep_reallocbitmap(int xsize,int ysize,Pbitmap pb);
void mdep_freebitmap(Pbitmap pb);
void mdep_movebitmap(int fromx0,int fromy0,int width,int height,int tox0,int toy0);
void mdep_pullbitmap(int x0,int y0,Pbitmap pb);
void mdep_putbitmap(int x0,int y0,Pbitmap pb);
int mdep_mouse(int *ax,int *ay, int *am);
int mdep_mousewarp(int x, int y);
void mdep_color(int n);
void mdep_colormix(int n,int r,int g,int b);
void mdep_sync(void);
char * mdep_fontinit(char *fnt);
int mdep_fontheight(void);
int mdep_fontwidth(void);
void mdep_string(int x, int y, char *s);
void mdep_setcursor(int type);
int udp_send(PORTHANDLE mp,char *msg,int msgsize);
PORTHANDLE * mdep_openport(char *name, char *mode, char *type);
Datum mdep_ctlport(PORTHANDLE m, char *cmd, char *arg);
int mdep_putportdata(PORTHANDLE m, char *buff, int size);
int mdep_getportdata(PORTHANDLE *handle, char *buff, int buffsize, Datum *pd);
int mdep_closeport(PORTHANDLE m);
int mdep_help(char *fname,char *keyword);
char * mdep_localaddresses(Datum d);
int my_ntohl(int v);

int mgetc(void);
void k_header(int f,int n,int d);
void k_starttrack(void);
void putnfree(void);
void putallnotes(void);
void k_endtrack(void);
void k_noteon(int chan,int pitch,int vol);
Noteptr queuenote(int chan,int pitch,int vol,int type);
void k_noteoff(int chan,int pitch,int vol);
void k_pressure(int chan,int pitch,int press);
void k_controller(int chan,int control,int value);
void k_pitchbend(int chan,int msb,int lsb);
void k_program(int chan,int program);
void k_chanpressure(int chan,int press);
void threebytes(int c1,int c2,int c3);
void twobytes(int c1,int c2);
void queuemess(Unchar *mess,int leng);
void k_arbitrary(int leng,Unchar *mess);
void k_tempo(long tempo);
void k_timesig(unsigned nn,unsigned dd,unsigned cc,unsigned bb);
void k_keysig(unsigned sf,unsigned mi);
void k_chanprefix(unsigned c);
void k_seqnum(int n);
void k_smpte(unsigned hr,unsigned mn,unsigned se,unsigned fr,unsigned ff);
void k_metatext(int type,int leng,Unchar *mess);
int mftoarr(char *mfname,Htablep arr);

int mdep_getnmidi(char *buff,int buffsize,int *port);
void mdep_putnmidi(int n, char *cp, Midiport * pport);
int openmidiin(int i);
void mdep_endmidi(void);
int mdep_initmidi(Midiport *inputs, Midiport *outputs);
void handlemidioutput(long long lParam, int windevno);
#if KEYCAPTURE
int startvideo(void);
void stopvideo(void);
#endif
#if KEYDISPLAY
int startdisplay(int noborder, int width, int height);
#endif
void setvideogrid(int gx, int gy);
Datum mdep_mdep(int argc);
int openmidiout(int windevno);
int mdep_midi(int openclose, Midiport * p);
// void PutEvent(LPCIRCULARBUFFER lpBuf, LPEVENT lpEvent);

void chksched(char *str);
void psched(void);
void resetcurrphr(void);
void initmidiport(Midiport *p);
void startrealtime(void);
void clrcontroller(void);
void newtempo(long t);
void resetreal(void);
void finishoff(void);
void addandput(int port, int n0, int chan, int c1,int c2);
void chkinput(void);
void chkoutput(void);
Unchar * ustrchr(Unchar *pn,int n);
int chanofbyte(int b);
int execnt(Sched *s, Sched *pres);
void toomany(char *onoff);
void rc_on(Unchar *mess,int indx);
void rc_off(Unchar *mess,int indx);
void rc_mess(Unchar *mess,int indx);
void rc_messhandle(Unchar *mess,int indx, int chan);
void rc_control(Unchar *mess,int indx);
void rc_pressure(Unchar *mess,int indx);
void rc_program(Unchar *mess,int indx);
void rc_chanpress(Unchar *mess,int indx);
void rc_pitchbend(Unchar *mess,int indx);
void rc_sysex(Unchar *mess,int indx);
void rc_position(Unchar *mess,int indx);
void rc_song(Unchar *mess,int indx);
void rc_startstopcont(Unchar *mess,int indx);
void rc_clock(Unchar *mess,int indx);
void chkcontroller(int port, Unchar* mess);
Noteptr  qnote(int chan);
void noteon(Noteptr q);
void noteoff(Noteptr q);
void notemess(Noteptr q);
void ntrecord(Noteptr n);
void clrsched(Sched **as);
Sched * newsch(void);
void unsched(Task *t);
void freesch(Sched *s);
Sched * immsched(int type,long clicks,Ktaskp tp,int monitor);
long taskphr(Phrasep ph, long clicks, long rep, int monitor);
void schdwake(long clicks);

Pbitmap v_reallocbitmap(int x,int y,Pbitmap p);
int v_linenorm(Kwind *w,int ln);
void v_settextsize(Kwind *w);
void v_setxy(Kwind *w);
void drawsweep(Kwind *w,int type,int x0,int y0,int x1,int y1);
long sanequant(Kwind *w,long qnt);
void dosweepstart(Kwind *w,int type,long x0,long y0,Fifo *mf);
void redrawmenu(Kwind *w);
void mouseblock(Fifo *mf);
void xyquant(Kwind *w,long *amx,long *amy,long quant,long *aclk,long *apitch);
void getmxy(Datum d,int *amx,int *amy,int *amval);
void fixxy(Kwind *w,long *amx,long *amy);
void i_dosweepcont(void);
char * ptbuffer(Kwind *w,int c);
void v_string(char *s);
void wprint(char *s);
void v_stringwind(char *s,Kwind *w);
void v_echar(Kwind *w);
void v_textdo(Kwind *w,int butt,int x,int y);
void v_texttobottom(Kwind *w);
int toplnum_decr(Kwind *w);
int toplnum_incr(Kwind *w);
int textscrollupdate(Kwind *w,int mx,int my);
void v_scrolldisplay(Kwind *w);
void v_scrollbuff(Kwind *w);
void drawtextbar(Kwind *w);
void redrawtext(Kwind *w);

char * myre_compX(char *pat);
char *      myre_comp(char *pat);
int myre_exec(char *lp);
void myre_modw(char *s);
int myre_subs(char *src, char *dst);

long mdep_milliclock(void);
void mdep_resetclock(void);

void menustringat(Kwind *w,int itempos,int itemnum);
void menuconstruct(Kwind *w,int existing);
void m_menuitem(Kwind *w,Kitem *ki);
void menusetsize(Kwind *w, int x0, int y0, int x1, int y1);
void menucalcxy(Kwind *w);
void drawchoice(Kwind *w,int unhigh);
void highchoice(Kwind *w);
void unhighchoice(Kwind *w);
int boundit(int val,int mn,int mx);
int scrollupdate(Kwind *w,int mx,int my);
int menuchoice(Kwind *w,int x,int y);
void m_reset(void);
void m_init(void);
void m_menudo(Kwind *w,int b,int x,int y,int nodraw);
